### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by z0z0Official** [palant/autoconnect-comfyui#1]
Traceback (most recent call last):
  File "C:\ComfyUI Rebuild Rebuild\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI Rebuild Rebuild\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\autoconnect-comfyui\\__init__.py'

Cannot import C:\ComfyUI Rebuild Rebuild\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\autoconnect-comfyui module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI Rebuild Rebuild\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\autoconnect-comfyui\\__init__.py'

installation is the same as all other Comfyui nodes. (Gitbash from dir-git clone [link of node from github] restart comfyui) then I get this error. It's the only one that isn't working for me. Could it be because Comfyui was updated and it might not be compatible? is there a branch that does work? I was looking forward to using this, it would save me some time. I will keep an eye out for any replies.
Best of luck.

-Soltis

**Comment by palant** [comment]
This is not a custom node. As the instructions say, this repository belongs into `ComfyUI/web/extensions` directory.
